export enum ErrorCodes {
  SERVER_ERROR = 1,
  MISSING_PARAMS = 2,
  UNAUTHORIZED  = 3,
  FAILED_TO_SEND_CODE = 4,
  TOO_SOON_FOR_RESEND_CODE = 5,
  TOO_MANY_ATTEMPTS_LOCKED= 6,
  INVALID_OR_EXPIRED_CODE= 7,
  INVALID_CODE= 8,
  INVALID_ROLE = 9,
  FORBIDDEN = 10,
  USER_NOT_REGISTERED=11


}

